import { useMemo, useState } from 'react'
import { usePoll, useLoad } from '../lib/hooks'
import { indexer, mid } from '../lib/indexer'
import { useSession } from '../lib/session'
import { buildIntentPlan } from '../lib/strategy'
import { fmt, fmtPrice, fmtBps, shortAddr, ago } from '../lib/format'
import { Panel, Stat, Tag, Empty, LiveBadge } from '../components/ui'

const EXPLORER = 'https://suiscan.xyz/mainnet/object'

// DeepBook fee fields are 1e9-scaled fixed-point (1_000_000 == 10 bps).
const feeBps = (raw: number) => raw / 100_000

/**
 * Layer 5 — Market Creation Console.
 * Live: real PoolCreated events from mainnet (permissionless market creation
 * is already happening). The pool-creation form emits a TypeScript SDK
 * snippet that scripts/trade.ts (or a wallet-connected build) can execute.
 * The flash-loan seeder is a conceptual PTB preview for atomically seeding
 * both sides of a freshly created pool.
 */
export function BuilderConsole() {
  const { pool } = useSession()
  const events = usePoll(() => indexer.poolCreated(), 60_000, [])
  const pools = useLoad(() => indexer.pools())
  const ob = usePoll(() => indexer.orderbook(pool, 4), 5_000, [pool])
  const spot = mid(ob.data)

  // --- 6.2 pool creation form ---
  const [baseType, setBaseType] = useState('0x2::sui::SUI')
  const [quoteType, setQuoteType] = useState(
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )
  const [tick, setTick] = useState('0.001')
  const [lot, setLot] = useState('0.1')
  const [minSize, setMinSize] = useState('1')
  const [takerFeeBps, setTakerFeeBps] = useState('10')
  const [makerFeeBps, setMakerFeeBps] = useState('0')
  const [generated, setGenerated] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const generate = () => {
    setCopied(false)
    setGenerated(`// Generated by DeepBook Market OS
import { DeepBookClient } from '@mysten/deepbook-v3'
import { Transaction } from '@mysten/sui/transactions'

const db = new DeepBookClient({ address, env: 'mainnet', client })

const tx = new Transaction()
db.deepBook.createPermissionlessPool({
  baseCoinKey: 'NEW_BASE',    // ${baseType || '<base coin type>'}
  quoteCoinKey: 'NEW_QUOTE',  // ${quoteType}
  tickSize: ${tick},
  lotSize: ${lot},
  minSize: ${minSize},
  deepCoin: deepFeeCoin,      // 500 DEEP creation fee — fund this coin first
})(tx)

// Requested fee tier (taker ${takerFeeBps} bps / maker ${makerFeeBps} bps).
// Permissionless pools launch on DeepBook's protocol-default fee tier;
// governance can move this pool onto the tier above via a follow-up vote.`)
  }

  const copy = () => {
    if (!generated) return
    navigator.clipboard.writeText(generated)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  // --- 6.3 flash-loan seeder ---
  const [seedBase, setSeedBase] = useState(1000)
  const [seedQuote, setSeedQuote] = useState(800)
  const [seedRungs, setSeedRungs] = useState(4)
  const [seedWidthPct, setSeedWidthPct] = useState(2)

  const [baseSym, quoteSym] = pool.split('_')

  const seedPlans = useMemo(() => {
    if (spot <= 0) return null
    const askPlan = buildIntentPlan({
      kind: 'exit',
      midPrice: spot,
      totalQuantity: seedBase,
      rungs: seedRungs,
      widthPct: seedWidthPct,
      skew: 0,
    })
    const bidPlan = buildIntentPlan({
      kind: 'accumulate',
      midPrice: spot,
      totalQuantity: seedQuote / spot,
      rungs: seedRungs,
      widthPct: seedWidthPct,
      skew: 0,
    })
    return { askPlan, bidPlan }
  }, [spot, seedBase, seedQuote, seedRungs, seedWidthPct])

  const rungLiteral = (rungs: { price: number; quantity: number }[]) =>
    rungs.map((r) => `  { price: ${r.price}, quantity: ${r.quantity} }`).join(',\n')

  const seedSteps = seedPlans
    ? [
        {
          title: `1. Flash borrow ${fmt(seedBase)} ${baseSym}`,
          desc: `Borrow ${baseSym} with no upfront collateral for the life of this PTB — the loan must be returned in step 5 or the whole transaction aborts.`,
          code: `const [baseCoin, baseLoan] = db.flashLoans.borrowBaseAsset('${pool}', ${seedBase})(tx)`,
        },
        {
          title: `2. Place ask ladder — ${seedRungs} rungs, selling ${fmt(seedBase)} ${baseSym}`,
          desc: `Seed the sell side of the new book ${seedWidthPct}% above mid using the borrowed ${baseSym}.`,
          code: `const askRungs = [\n${rungLiteral(seedPlans.askPlan.rungs)},\n]\nfor (const r of askRungs) {\n  db.deepBook.placeLimitOrder({\n    poolKey: '${pool}',\n    balanceManagerKey: BM_KEY,\n    price: r.price,\n    quantity: r.quantity,\n    isBid: false,\n    payWithDeep: true,\n  })(tx)\n}`,
        },
        {
          title: `3. Flash borrow ${fmt(seedQuote)} ${quoteSym}`,
          desc: `Borrow ${quoteSym} for the buy side of the new book — also returned in step 5.`,
          code: `const [quoteCoin, quoteLoan] = db.flashLoans.borrowQuoteAsset('${pool}', ${seedQuote})(tx)`,
        },
        {
          title: `4. Place bid ladder — ${seedRungs} rungs, buying ~${fmt(seedQuote / spot)} ${baseSym}`,
          desc: `Seed the buy side ${seedWidthPct}% below mid using the borrowed ${quoteSym}.`,
          code: `const bidRungs = [\n${rungLiteral(seedPlans.bidPlan.rungs)},\n]\nfor (const r of bidRungs) {\n  db.deepBook.placeLimitOrder({\n    poolKey: '${pool}',\n    balanceManagerKey: BM_KEY,\n    price: r.price,\n    quantity: r.quantity,\n    isBid: true,\n    payWithDeep: true,\n  })(tx)\n}`,
        },
        {
          title: `5. Repay flash loans`,
          desc: `Return both loans from the ladder's initial fills, or top up from a pre-existing BalanceManager balance — both must be repaid in full within this PTB.`,
          code: `db.flashLoans.returnBaseAsset('${pool}', ${seedBase}, baseCoin, baseLoan)(tx)\ndb.flashLoans.returnQuoteAsset('${pool}', ${seedQuote}, quoteCoin, quoteLoan)(tx)`,
        },
      ]
    : []

  const recent = (events.data ?? [])
    .slice()
    .sort((a, b) => b.checkpoint_timestamp_ms - a.checkpoint_timestamp_ms)
    .slice(0, 12)

  return (
    <div>
      <div className="screen-head">
        <h2>Builder / Market Creation Console</h2>
        <p>Create new DeepBook pools and generate the SDK code to launch and seed them</p>
        <LiveBadge ok={!!events.data} />
      </div>

      <div className="stat-row">
        <Stat label="Pools live on mainnet" value={pools.data?.length ?? '—'} />
        <Stat label="Creation events indexed" value={events.data?.length ?? '—'} hint="60s poll" />
        <Stat label="Creation fee" value="500 DEEP" hint="permissionless pool creation" />
        <Stat label={`${pool} spot (live)`} value={fmtPrice(spot)} hint="reference price for the seeder below" />
      </div>

      <div className="screen-grid cols-2">
        <Panel
          title="New market — pool creation form"
          sub="Generates a TypeScript SDK snippet to create a permissionless DeepBook pool"
        >
          <div className="form-row">
            <label className="fld" style={{ flex: 2 }}>
              base asset (type)
              <input
                value={baseType}
                placeholder="0x2::sui::SUI"
                onChange={(e) => setBaseType(e.target.value)}
              />
            </label>
          </div>
          <div className="form-row">
            <label className="fld" style={{ flex: 2 }}>
              quote asset (type)
              <input value={quoteType} onChange={(e) => setQuoteType(e.target.value)} />
            </label>
          </div>
          <div className="form-row">
            <label className="fld">
              tick size
              <input value={tick} onChange={(e) => setTick(e.target.value)} />
            </label>
            <label className="fld">
              lot size
              <input value={lot} onChange={(e) => setLot(e.target.value)} />
            </label>
            <label className="fld">
              min size
              <input value={minSize} onChange={(e) => setMinSize(e.target.value)} />
            </label>
          </div>
          <div className="form-row">
            <label className="fld">
              taker fee (bps)
              <input
                type="number"
                value={takerFeeBps}
                onChange={(e) => setTakerFeeBps(e.target.value)}
              />
            </label>
            <label className="fld">
              maker fee (bps)
              <input
                type="number"
                value={makerFeeBps}
                onChange={(e) => setMakerFeeBps(e.target.value)}
              />
            </label>
          </div>
          <button className="btn" onClick={generate}>
            Generate creation transaction
          </button>
          <p className="note" style={{ marginTop: 8 }}>
            Creating a pool costs 500 DEEP (creation fee). Execute this with a funded wallet.
          </p>
          {generated && (
            <>
              <pre className="code" style={{ marginTop: 4 }}>
                {generated}
              </pre>
              <button className="btn ghost" onClick={copy}>
                {copied ? 'copied!' : 'copy'}
              </button>
            </>
          )}
        </Panel>

        <Panel
          title="Live pool-creation feed (mainnet)"
          sub="Real PoolCreated events, 60s poll — proof permissionless market creation is already in motion"
        >
          {recent.length ? (
            <table className="tbl">
              <thead>
                <tr>
                  <th>When</th>
                  <th>Pool</th>
                  <th>Creator</th>
                  <th className="num">Taker fee</th>
                  <th className="num">Maker fee</th>
                  <th className="num">Tick</th>
                  <th className="num">Lot</th>
                  <th className="num">Min size</th>
                  <th>Type</th>
                </tr>
              </thead>
              <tbody>
                {recent.map((e) => (
                  <tr key={e.event_digest}>
                    <td>{ago(e.checkpoint_timestamp_ms)}</td>
                    <td>
                      <a href={`${EXPLORER}/${e.pool_id}`} target="_blank" rel="noreferrer" title={e.pool_id}>
                        {shortAddr(e.pool_id)}
                      </a>
                    </td>
                    <td title={e.sender}>{shortAddr(e.sender)}</td>
                    <td className="num">{fmtBps(feeBps(e.taker_fee))}</td>
                    <td className="num">{fmtBps(feeBps(e.maker_fee))}</td>
                    <td className="num">{fmt(e.tick_size, 6)}</td>
                    <td className="num">{fmt(e.lot_size, 4)}</td>
                    <td className="num">{fmt(e.min_size, 4)}</td>
                    <td>
                      <Tag tone={e.whitelisted_pool ? 'live' : 'info'}>
                        {e.whitelisted_pool ? 'whitelisted' : 'permissionless'}
                      </Tag>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <Empty
              text={events.error ? `indexer: ${events.error}` : 'loading creation events…'}
              tone={events.error ? 'error' : undefined}
            />
          )}
        </Panel>

        <Panel
          className="span-all"
          title="Flash-loan seeder (PTB preview — requires funded wallet to execute)"
          sub={`Atomically seed both sides of a new ${pool}-style book in one PTB: borrow, ladder, repay from the fills. Uses ${pool}'s live mid as the reference price.`}
        >
          <div className="form-row">
            <label className="fld">
              flash-borrow {baseSym} (X)
              <input
                type="number"
                value={seedBase}
                onChange={(e) => setSeedBase(+e.target.value || 0)}
              />
            </label>
            <label className="fld">
              flash-borrow {quoteSym} (Y)
              <input
                type="number"
                value={seedQuote}
                onChange={(e) => setSeedQuote(+e.target.value || 0)}
              />
            </label>
            <label className="fld">
              rungs per side
              <input
                type="number"
                min={1}
                max={10}
                value={seedRungs}
                onChange={(e) => setSeedRungs(+e.target.value || 1)}
              />
            </label>
            <label className="fld">
              ladder width %
              <input
                type="number"
                min={0.1}
                step="0.5"
                value={seedWidthPct}
                onChange={(e) => setSeedWidthPct(+e.target.value || 0.1)}
              />
            </label>
          </div>

          {seedSteps.length ? (
            <div className="screen-grid cols-2" style={{ marginTop: 4 }}>
              {seedSteps.map((s) => (
                <div key={s.title} className="panel" style={{ padding: 12 }}>
                  <div style={{ fontWeight: 650, marginBottom: 4 }}>{s.title}</div>
                  <p className="note" style={{ marginTop: 0, marginBottom: 6 }}>
                    {s.desc}
                  </p>
                  <pre className="code">{s.code}</pre>
                </div>
              ))}
            </div>
          ) : (
            <Empty text="waiting for live spot…" />
          )}

          <p className="note" style={{ marginTop: 8 }}>
            All five steps run inside a single PTB built with <code>db.flashLoans.*</code> and{' '}
            <code>db.deepBook.placeLimitOrder</code> (<code>BM_KEY</code> = your funded
            BalanceManager, see <code>lib/deepbook.ts</code>). If the ladders don't fully fill
            within the same transaction, top up the BalanceManager beforehand so step 5 can
            repay from existing balance — flash loans that aren't repaid revert the entire PTB.
          </p>
        </Panel>
      </div>
    </div>
  )
}
